var fullName = 'Alex Piper';
console.log('value of fullName:', fullName);
var isCool = true;
console.log('value of isCool:', isCool);
var totalPets = 1;
console.log('value of totalPets:', totalPets);
console.log('typeof fullName:', typeof fullName);
console.log('type of isCool:', typeof isCool);
console.log('type of totalPets:', typeof totalPets);
var unknown = null;
console.log('value of unknown:', unknown);
console.log('typeof unknown:', typeof unknown);
var never;
console.log('value of never', never);
console.log('typeof never', typeof never);
